.Dd 7/8/14
.Dt hs 1
.Os Darwin
.Sh NAME
.Nm hs
.Nd Command line interface to Hammerspoon.app
.Sh SYNOPSIS
.Nm
.Op Fl i | Fl s | Fl c Ar code | Fl t Ar timeout
.Op Fl r
.Op Fl n
.Sh DESCRIPTION
Runs
.Ar code
from within Hammerspoon, and prints the results. The given
.Ar code
is passed to "hs.ipc.handler" which normally executes it as plain Lua code, but may be overridden to do some custom evaluation.
.Pp
When no args are given,
.Fl i
is implied.
.Pp
.Bl -tag -width -indent
.It Fl i
Runs in interactive-mode; uses each line as
.Ar code
\&. Prints in color unless otherwise specified.
.It Fl c
Uses the given argument as
.Ar code
.It Fl t
Uses the given argument
.Ar timeout
as the receive timeout, instead of the default of 4 seconds.
.It Fl s
Uses stdin as
.Ar code
.It Fl r
Forces Hammerspoon to interpret
.Ar code
as raw Lua code; the function "hs.ipc.handler" is not called.
.It Fl n
When specified, interactive-mode does not use colors.
.El
.Pp
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
