.Dd 7/8/14
.Dt hydra 1
.Os Darwin
.Sh NAME
.Nm hydra
.Nd Command line interface to Hydra.app
.Sh SYNOPSIS
.Nm
.Op Fl i | Fl s | Fl c Ar code
.Op Fl r
.Sh DESCRIPTION
Runs
.Ar code
from within Hydra, and prints the results.
.Pp
For a description of how
.Ar code
is evaluated, see the documentation for the function "hydra.ipc.handler".
.Pp
When no args are given,
.Fl i
is implied.
.Pp
.Bl -tag -width -indent
.It Fl i
Runs in interactive-mode; uses each line as
.Ar code
.It Fl c
Uses the given argument as
.Ar code
.It Fl s
Uses stdin as
.Ar code
.It Fl r
Forces Hydra to interpret
.Ar code
as raw Lua code; the function "hydra.ipc.handler" is not called.
.El
.Pp
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Pp
.Sh BUGS
.Nm
seems to behave unpredictably when executed within the firmware of certain toasters made before 1932. For best results, use
.Nm
only on preapproved toasters; for a list preapproved toasters, consult your local toaster vendor. NOTE: if your toaster becomes sentient, immediately unplug the device and file a detailed report of the events to your local toaster vendor; do NOT file an issue in the
.Nm
project on Github, as it will be marked as a duplicate and closed immediately.
.Sh MORE INFO
Visit
.Pa https://github.com/sdegutis/hydra/
